export default {
  attachment: 'attachment',
  cloudCircle: 'cloud_circle',
  cloudDone: 'cloud_done',
  cloudDownload: 'cloud_download',
  cloudOff: 'cloud_off',
  cloudQueue: 'cloud_queue',
  cloudUpload: 'cloud_upload',
  cloud: 'cloud',
  fileDownload: 'file_download',
  fileUpload: 'file_upload',
  folderOpen: 'folder_open',
  folderShared: 'folder_shared',
  folder: 'folder',
};
