export default {
  apps: 'apps',
  arrowBack: 'arrow_back',
  arrowDropDownCircle: 'arrow_drop_down_circle',
  arrowDropDown: 'arrow_drop_down',
  arrowDropUp: 'arrow_drop_up',
  arrowForward: 'arrow_forward',
  cancel: 'cancel',
  check: 'check',
  chevronLeft: 'chevron_left',
  chevronRight: 'chevron_right',
  close: 'close',
  expandLess: 'expand_less',
  expandMore: 'expand_more',
  fullscreenExit: 'fullscreen_exit',
  fullscreen: 'fullscreen',
  menu: 'menu',
  moreHoriz: 'more_horiz',
  moreVert: 'more_vert',
  refresh: 'refresh',
  unfoldLess: 'unfold_less',
  unfoldMore: 'unfold_more',
};
