export default {
  cake: 'cake',
  domain: 'domain',
  groupAdd: 'group_add',
  group: 'group',
  locationCity: 'location_city',
  moodBad: 'mood_bad',
  mood: 'mood',
  notificationsActive: 'notifications_active',
  notificationsNone: 'notifications_none',
  notificationsOff: 'notifications_off',
  notificationsPaused: 'notifications_paused',
  notifications: 'notifications',
  pages: 'pages',
  partyMode: 'party_mode',
  peopleOutline: 'people_outline',
  people: 'people',
  personAdd: 'person_add',
  personOutline: 'person_outline',
  person: 'person',
  plusOne: 'plus_one',
  poll: 'poll',
  public: 'public',
  school: 'school',
  share: 'share',
  whatshot: 'whatshot',
};
